spring:
    datasource:
      url: "${SUPABASE_URL}"
      username: "${SUPABASE_USER}"
      password: "${SUPABASE_PASSWORD}"
      driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update   # options: none, validate, update, create, create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database-platform: